---
- name: remove packages
  apt: name={{ item }} state=absent
  with_items:
    - "{{ purge_packages }}"

- name: install additional packages
  apt: name={{ item }} state=latest
  with_items:
    - "{{ install_packages }}"

- name: allow everything and enable ufw
  ufw: state=enabled policy=allow

#- name: deny 4gpi interface
#  ufw: rule=deny direction=in interface={{ item }}
#  with_items:
#    - ppp0
#    - wwan0

- name: purge unused packages
  include_role:
    name: common
    tasks_from: autopurge

- name: upgrade packages
  apt: upgrade=dist

- name: purge unused packages
  include_role:
    name: common
    tasks_from: autopurge

- name: enable timesync service
  command: timedatectl set-ntp true

# reboot
- name: Unconditionally reboot the machine with all defaults
  reboot:

# wait
- name: Wait 600 seconds for target connection to become reachable/usable
  wait_for_connection:

# hwclock -w
- name: write system clock into RTC
  command: hwclock -w

- name: disable timesync service
  command: timedatectl set-ntp false

- name: Unconditionally reboot the machine with all defaults
  reboot:

# wait
- name: Wait 600 seconds for target connection to become reachable/usable
  wait_for_connection:

# TODO:個別コピー？
#- name: copy config files
#  copy: src=./ dest=/ owner=root group=root mode=0644
